import { useState } from "react";

import { getReportCatalog, getRiskBreakdown, getFundingChartData, RECENT_REPORTS } from "../data/reportsData";
import DonutChart from "../components/DonutChart";
import ColumnChart from "../components/ColumnChart";
import LineChart from "../components/LineChart";


function Reports() {

  const catalog = getReportCatalog();
  const [generated, setGenerated] = useState(null);

  const riskData = getRiskBreakdown();
  const riskTotal = riskData.reduce((sum, d) => sum + d.value, 0);
  const { allocation, quarterly } = getFundingChartData();

  const handleGenerate = (label) => {
    setGenerated(label);
    window.setTimeout(() => setGenerated(null), 2500);
  };

  return (

    <div className="central-dashboard tabbed-module">

      <div className="tabbed-module-header">
        <h2>Reports</h2>
        <p>
          Generate reports pulling live counts from Projects, Land &amp;
          Impact and Funding. Export to PDF/XLSX isn't wired to a document
          service yet — this is the catalog and request flow.
        </p>
      </div>

      {generated && (
        <div className="module-note" style={{ borderColor: "var(--accent-green-border)", background: "var(--accent-green-bg)" }}>
          <strong>{generated}</strong> would be generated here once report
          export is connected to a document service.
        </div>
      )}

      <div className="reports-chart-grid">

        <div className="dashboard-panel">
          <div className="dashboard-panel-header">
            <h3>Projects by Risk Level</h3>
            <span>{riskTotal} projects tracked</span>
          </div>
          <DonutChart data={riskData} centerLabel="Projects" centerValue={riskTotal} />
        </div>

        <div className="dashboard-panel">
          <div className="dashboard-panel-header">
            <h3>Fund Allocation by Category</h3>
            <span>₹ Cr, planning figures</span>
          </div>
          <ColumnChart data={allocation.map((a) => ({ label: a.label, value: a.amount, color: a.color }))} />
        </div>

      </div>

      <div className="dashboard-panel" style={{ marginBottom: "1.1rem" }}>
        <div className="dashboard-panel-header">
          <h3>Quarterly Allocated vs. Utilized</h3>
          <span>Illustrative pacing — sums to real totals</span>
        </div>
        <LineChart
          series={[
            { label: "Allocated", color: "var(--series-1)", points: quarterly.map((q) => ({ label: q.quarter, value: q.allocated })) },
            { label: "Utilized", color: "var(--accent-green)", points: quarterly.map((q) => ({ label: q.quarter, value: q.utilized })) },
          ]}
          valueSuffix=" Cr"
        />
      </div>

      <div className="impact-category-grid" style={{ marginBottom: "1.1rem" }}>

        {catalog.map((r) => (
          <div key={r.key} className="impact-category-card">
            <div className="impact-category-title">
              <span className="impact-category-icon">{r.icon}</span>
              {r.label}
            </div>
            <p className="land-note" style={{ marginBottom: "0.9rem" }}>{r.description}</p>
            <button type="button" className="settings-btn" onClick={() => handleGenerate(r.label)}>
              Generate Report →
            </button>
          </div>
        ))}

      </div>

      <div className="dashboard-panel">
        <div className="dashboard-panel-header">
          <h3>Recent Reports</h3>
          <span>Illustrative — report history isn't tracked yet</span>
        </div>

        <div className="data-table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Report</th>
                <th>Type</th>
                <th>Generated On</th>
                <th>Generated By</th>
                <th>Format</th>
              </tr>
            </thead>
            <tbody>
              {RECENT_REPORTS.map((r) => (
                <tr key={r.id}>
                  <td>{r.name}</td>
                  <td>{r.type}</td>
                  <td>{r.generatedOn}</td>
                  <td>{r.generatedBy}</td>
                  <td>{r.format}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>

  );

}

export default Reports;
